@order-service = order-service--aie3a2s.blackglacier-66b40556.southcentralus.azurecontainerapps.io
##@order-service = order-service--973lvth.mangohill-f5b6c8b4.southcentralus.azurecontainerapps.io
@order-service-dapr = order-service--aie3a2s.blackglacier-66b40556.southcentralus.azurecontainerapps.io:5180
@storeId = Redmond

### Create an order via order-service POST
POST https://{{order-service}}/order
Content-Type: application/json
 
{
    "storeId": "{{storeId}}",
    "firstName": "John 'Hannibal'",
    "lastName": "Smith",
    "loyaltyId": "42",
    "orderItems": [
        {
            "menuItemId": 1,
            "quantity": 1
        },
        {
            "menuItemId": 2,
            "quantity": 1
        },
        {
            "menuItemId": 3,
            "quantity": 3
        }
    ]
}

### Get Products
GET http://{{order-service}}/product

### Publish an order via order-service dapr sidecar
POST http://{{order-service-dapr}}/v1.0/publish/{{pubsubName}}/orders
Content-Type: application/json

{
    "orderId": "{{$guid }}",
    "orderDate": "{{$datetime iso8601}}",
    "storeId": "{{storeId}}",
    "firstName": "John 'Hannibal'",
    "lastName": "Smith",
    "loyaltyId": "42",
    "orderTotal": 2.99,
    "orderItems": [{
        "menuItemId": 1,
        "menuItemName": "Americano",
        "quantity": 1
    }]
}